<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'csa_guzzle.subscriber.stopwatch' shared service.

return $this->services['csa_guzzle.subscriber.stopwatch'] = new \Csa\Bundle\GuzzleBundle\GuzzleHttp\Subscriber\StopwatchSubscriber(${($_ = isset($this->services['debug.stopwatch']) ? $this->services['debug.stopwatch'] : $this->services['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)) && false ?: '_'});
