<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO8mryvn\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO8mryvn/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerO8mryvn.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerO8mryvn\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerO8mryvn\appDevDebugProjectContainer(array(
    'container.build_hash' => 'O8mryvn',
    'container.build_id' => '7a63c424',
    'container.build_time' => 1537960241,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerO8mryvn');
